language: go

go:
  - 1.14.x

addons:
  apt:
    packages:
      - libusb-1.0-0-dev

services:
  docker

env:
  - GO111MODULE=on

jobs:
  include:
    - name: linux-amd64
      os: linux
      dist: xenial
      arch: amd64
    - name: linux-arm64
      os: linux
      dist: xenial
      arch: arm64

branches:
  only:
    - master

script:
  - make build
  - make docker-build
  - make archive OS=${TRAVIS_OS_NAME} ARCH=${TRAVIS_CPU_ARCH}

before_deploy:
  - export TRAVIS_TAG="v$(cat VERSION)"

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file_glob: true
  file:
    - dist/*.tar.gz
  skip_cleanup: true
  overwrite: true
  draft: true

after_deploy:
  - make clean
