language: go

go:
  - 1.14.x

arch:
  - amd64
  - arm64

addons:
  apt:
    packages:
      - libusb-1.0-0-dev

services:
  docker

env:
  - GO111MODULE=on

branches:
  only:
    - master

script:
  - make build
  - make docker-build
  - make archive OS=${TRAVIS_OS_NAME} ARCH=${TRAVIS_CPU_ARCH}

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file:
    - dist/*.tar.gz
  overwrite: true

after_deploy:
  - make clean
