language: go

go:
  - 1.14.x

arch:
  - amd64
  - arm64

addons:
  apt:
    packages:
      - libusb-1.0-0-dev

services:
  docker

env:
  - GO111MODULE=on

branches:
  only:
    - master

matrix:
  include:
    - name: linux-amd64
      os: linux
      dist: xenial
      arch: amd64
    - name: linux-arm64
      os: linux
      dist: xenial
      arch: arm64

script:
  - make build
  - make build-docker
  - make archive OS=${TRAVIS_OS_NAME} ARCH=${TRAVIS_CPU_ARCH}

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file:
    - dist/*.tar.gz
  skip_cleanup: true
  overwrite: true

after_deploy:
  - make clean
